name: trunk breakpoint
description: Set conditional breakpoints for your GitHub Actions. Securely pause/debug/resume your jobs
author: trunk.io
branding:
  icon: terminal
  color: gray-dark
inputs:
  breakpoint_id: # id of breakpoint
    description: Which breakpoint to trigger
    required: true
  run: # Command to run
    description: Which command to run
    required: true
  trunk_token:
    description: API key for trunk. Should be in your secrets
    required: true
  debug:
    description: Add debug level logs
    default: false
    required: false
  shell:
    description: Which shell to run with
    default: bash
    required: false
runs:
  using: composite
  steps:
    - run: curl https://get.trunk.io -fsSL | bash
    - run: |
        trunk breakpoint --debug=${{ inputs.debug }} --id="${{ inputs.breakpoint_id }}" -- "${{ inputs.run }}"
      shell: ${{ inputs.shell }}
      env:
        TRUNK_CLI_VERSION: 1.11.0
        TRUNK_GITHUB_CONTEXT: ${{ toJSON(github) }}
        TRUNK_TOKEN: ${{ inputs.trunk_token }}
        SHELL: ${{ inputs.shell }}
        GH_TOKEN: ${{ github.token }}
        TRUNK_LAUNCHER_QUIET: 1
