name: Breakpoint
description: Set up a trunk breakpoint
inputs:
  breakpoint_id: # id of breakpoint
    description: Which breakpoint to trigger
    required: true
  run: # Command to run
    description: Which command to run 
    required: true
  trunk_token:
    description: API key for trunk. Should be in your secrets
    required: true
  debug:
    description: Add debug level logs
    default: false
    required: false
  shell:
    description: Which shell to run with
    default: bash
    required: false
runs:
  using: composite
  steps:
    - name: Install github tools
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y) 
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y
      shell: bash
    - name: Run affected tests
      run: |
        trunk breakpoint --debug=${{ inputs.debug }} --id="${{ inputs.breakpoint_id }}" -- "${{ inputs.run }}" 
      shell: ${{ inputs.shell }}
      env:
        TRUNK_GITHUB_CONTEXT: ${{ toJSON(github) }}
        TRUNK_TOKEN: ${{ inputs.trunk_token }}
        SHELL: ${{ inputs.shell }}
        GH_TOKEN: ${{ github.token }}
        TRUNK_LAUNCHER_QUIET: 1
