name: Pull Request
on:
  - pull_request

permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing code
        uses: ./
        with:
          breakpoint-id: run-tests
          run: ./tests/run_tests
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
